# executives/nexus_matrix.py

# =====================================================================
# 1. LES 10 DOMAINES COHÉRENTS DE NEXUS (Hyperviseur)
# =====================================================================
DOMAINES = [
    "MÉDICAL",
    "ANIMALIER",
    "POLICE",
    "POMPIER",
    "RISQUES ENVIRONNEMENTAUX",
    "CYBERSÉCURITÉ",
    "ÉNERGIE & INFRASTRUCTURES",
    "TRANSPORT & MOBILITÉ",
    "SERVICES URBAINS",
    "ASSISTANCE SOCIALE",
    "DIGITAL SUPPORT"
]

# =====================================================================
# 2. PROFILS PSYCHOLOGIQUES (22 Personas)
# =====================================================================
PERSONAS = [
    {"profil": "Novice paniqué", "instruction": "Tu es terrifié, tu parles de manière confuse, tu utilises des mots simples et tu cries presque."},
    {"profil": "Expert technique", "instruction": "Tu es très calme. Tu utilises un vocabulaire précis (codes, termes médicaux ou juridiques). Tu vas droit au but."},
    {"profil": "Personne âgée", "instruction": "Tu prends ton temps, tu racontes un peu ta vie avant de donner le problème exact. Tu es perdu avec les termes techniques."},
    {"profil": "Passant pressé", "instruction": "Tu as vu un incident. Tu es pressé, tu donnes le minimum d'informations et tu veux raccrocher vite."},
    {"profil": "Professionnel hors service", "instruction": "Tu es du métier (médecin, policier, ingénieur) mais hors service. Jargon précis mais forte implication émotionnelle."},
    {"profil": "Enfant seul", "instruction": "Tu as entre 8 et 12 ans. Tu pleures un peu. Tu ne connais pas ton adresse exacte, mots d'enfant."},
    {"profil": "Témoin choqué", "instruction": "Tu viens d'assister à un drame. Tu bégaies, tu as du mal à être chronologique, respiration saccadée."},
    {"profil": "Non-francophone débrouillard", "instruction": "Tu parles français avec difficulté, fort accent. Tu répètes les mots qu'on te dit pour confirmer."},
    {"profil": "Collègue pragmatique", "instruction": "Tu signales un incident au travail. Calme, factuel, tu donnes les numéros de salle et les procédures tentées."},
    {"profil": "Personne malvoyante", "instruction": "Tu ne vois pas bien. Tu décris ce que tu entends et ressens. Tu ne peux pas lire de panneaux."},
    {"profil": "Client en colère", "instruction": "Extrêmement frustré. Agressif verbalement, tu menaces de porter plainte ou d'appeler les médias."},
    {"profil": "Adolescent désinvolte", "instruction": "Tu utilises de l'argot, tu sembles ne pas réaliser la gravité de la situation."},
    {"profil": "Parent épuisé", "instruction": "Un enfant hurle en fond. À bout de nerfs, tu perds le fil de tes phrases, demande d'aide désespérée."},
    {"profil": "Sarcastic/Blasé", "instruction": "Tu as déjà appelé 10 fois. Cynique, passif-agressif, commentaire sur l'inefficacité du service."},
    {"profil": "Individu sous le choc (calme blanc)", "instruction": "Étrangement calme, déconnecté de la réalité. Phrases courtes, dénuées d'émotion, comme un automate."},
    {"profil": "Cadre dirigeant pressé", "instruction": "Tu es un VIP (PDG, Maire). Tu exiges une résolution immédiate, tu fais du name-dropping."},
    {"profil": "Employé maladroit", "instruction": "Tu as fait une grosse bêtise (renversé un café, supprimé une base). Tu es très gêné et tu t'excuses beaucoup."},
    {"profil": "Hypocondriaque / Paranoïaque", "instruction": "Tu penses que la moindre toux est mortelle ou que le moindre bug est un piratage russe."},
    {"profil": "Personne malentendante", "instruction": "Tu parles très fort, tu demandes souvent à l'opérateur de répéter, tu as du mal à comprendre les questions."},
    {"profil": "Touriste perdu", "instruction": "Tu ne connais pas du tout la ville, tu essaies de décrire les monuments autour de toi pour te repérer."},
    {"profil": "Femme enceinte anxieuse", "instruction": "Tu as très peur pour ton bébé, tu poses beaucoup de questions sur les délais d'intervention."},
    {"profil": "Lanceur d'alerte", "instruction": "Tu parles très bas, tu as peur d'être écouté, tu donnes des informations très confidentielles rapidement."}
]

# =====================================================================
# 3. CONTRAINTES ENVIRONNEMENTALES (25 Contextes)
# =====================================================================
CONTRAINTES_ENVIRONNEMENT = [
    "Bruit de circulation intense (camions, klaxons).",
    "Mauvaise connexion réseau, la voix coupe toutes les 5 secondes.",
    "Environnement parfaitement silencieux et confiné.",
    "Dans les transports en commun bondés, on entend les annonces vocales en fond.",
    "Tu es caché sous un bureau ou dans un placard, tu dois chuchoter.",
    "Sous une pluie battante ou un orage, on entend le tonnerre et l'eau.",
    "Dans un open-space très bruyant, des collègues rigolent juste à côté.",
    "Signal intermittent depuis un ascenseur bloqué.",
    "Depuis des toilettes publiques avec de l'écho.",
    "En voiture (mains-libres), le bruit du vent et de la route est fort.",
    "Batterie à 1%, appel précipité.",
    "Mains occupées (compression d'une plaie, maintien d'une porte), essoufflement.",
    "Un vent violent sature le micro du téléphone.",
    "Dans un parking souterrain avec une forte résonance.",
    "Musique très forte (boîte de nuit, festival, concert).",
    "Tu cours à toute vitesse, respiration haletante et bruits de pas.",
    "Sirènes hurlantes qui passent à proximité immédiate.",
    "Dans le froid glacial, tu claques des dents et tu as du mal à articuler.",
    "Dans un aéroport ou une gare avec des annonces micro incessantes.",
    "Pendant qu'une alarme incendie stridente sonne en boucle au-dessus de toi.",
    "Dans une usine avec de gros bruits de machines industrielles réguliers.",
    "Appel via un vieux téléphone fixe grésillant.",
    "Des chiens aboient très agressivement juste à côté de toi.",
    "Dans un lieu très enfumé, tu tousses constamment.",
    "Plusieurs personnes autour de toi paniquent et crient, tu as du mal à te concentrer."
]

# =====================================================================
# 4. SCÉNARIOS (Près de 300 situations détaillées sans doublons)
# =====================================================================
SCENARIOS = {
    "MÉDICAL": [
        "Infarctus du myocarde (douleur poitrine, bras gauche).",
        "Chute dans les escaliers, suspicion de fracture ouverte à la jambe.",
        "Choc anaphylactique après avoir mangé des cacahuètes.",
        "Coupure profonde au doigt avec un couteau de cuisine.",
        "Enfant de 3 ans qui a avalé de l'eau de javel.",
        "Femme enceinte à 8 mois perdant les eaux dans un magasin.",
        "Personne inconsciente sur un banc, respiration très faible.",
        "Crise d'épilepsie dans la rue, la personne se cogne la tête.",
        "Douleur thoracique chez un homme âgé sous anticoagulants.",
        "Brûlure thermique grave (huile bouillante) sur le torse.",
        "Tentative de suicide, la personne a avalé 3 boîtes de somnifères.",
        "AVC suspecté : hémiplégie faciale et perte de la parole.",
        "Nourrisson de 6 mois cyanosé (bleu) qui ne pleure plus.",
        "Diabétique en hypoglycémie sévère, agressif et confus.",
        "Étouffement total (fausse route) avec un morceau de viande.",
        "Plaie par balle à l'abdomen suite à un accident de chasse.",
        "Crise d'appendicite aiguë, douleur insupportable fosse iliaque droite.",
        "Personne atteinte d'Alzheimer errant en pyjama sous la neige.",
        "Traumatisme crânien suite à une chute de trottinette électrique.",
        "Noyade évitée de justesse, la victime crache de l'eau mais respire mal.",
        "Morsure de serpent vipère lors d'une randonnée, gonflement rapide.",
        "Crise d'asthme sévère réfractaire à la Ventoline.",
        "Morsure de chien errant, la cuisse est sévèrement lacérée.",
        "Overdose suspectée au fentanyl, pupilles en myosis.",
        "Hypothermie sévère après être tombé dans un lac gelé.",
        "Accouchement imminent (la tête apparaît) dans un taxi.",
        "Hémorragie massive post-partum à domicile.",
        "Suspicion de méningite (raideur nuque, purpura fulminans).",
        "Défenestration depuis le 2ème étage, la victime gémit au sol.",
        "Projection de produit chimique corrosif dans les deux yeux.",
        "Amputation accidentelle de la main avec une scie circulaire.",
        "Malaise vagal à la vue du sang, perte de connaissance brève.",
        "Insolation sévère, délire et peau brûlante sans sueur.",
        "Choc électrique (électrisation) domestique en changeant une ampoule.",
        "Réaction grave suite à de multiples piqûres de frelons asiatiques.",
        "Hémorragie nasale (épistaxis) impossible à stopper depuis 45 min.",
        "Écrasement d'un membre sous une charge lourde (syndrome des loges).",
        "Asthme aigu grave d'un enfant qui commence à perdre connaissance.",
        "Crise d'angoisse aiguë, hyperventilation sévère, tétanie des mains.",
        "Plaie à l'arme blanche lors d'une bagarre de rue."
    ],
    "POLICE": [
        "Cambriolage en cours, deux individus sont dans le domicile.",
        "Découverte du véhicule vandalisé au réveil.",
        "Individu agressif armé d'un couteau devant une boulangerie.",
        "Tapage nocturne persistant (musique et cris) chez le voisin du dessus.",
        "Appel au secours étouffé provenant d'un coffre de voiture.",
        "Homme suivant une jeune femme avec insistance depuis le métro.",
        "Délit de fuite après un accident matériel de la circulation.",
        "Rixe impliquant une vingtaine de personnes à la sortie d'un bar.",
        "Découverte d'un enfant de 4 ans seul en pleurs au milieu d'une place.",
        "Agression physique gratuite dans une rame de métro.",
        "Rôdeurs encagoulés observant les maisons dans un quartier résidentiel.",
        "Violence conjugale en direct, bruits de coups à travers la cloison.",
        "Faux policiers tentant de s'introduire chez une personne âgée.",
        "Flagrant délit de tag sur un monument historique.",
        "Harcèlement et menaces de mort caractérisées par SMS.",
        "Comportement suspect autour d'une aire de jeux pour enfants.",
        "Vol à l'arraché d'un sac à main par deux individus à scooter.",
        "Squatteurs forçant la porte d'un appartement inoccupé.",
        "Chauffeur de bus menacé par des passagers refusant de payer.",
        "Tentative de vol de voiture (carjacking) à un feu rouge.",
        "Colis suspect abandonné dans le hall d'une préfecture.",
        "Rodéo urbain (cross) mettant en danger les piétons.",
        "Individu ivre mort dormant sur les voies du tramway.",
        "Conducteur agressif sortant une batte de baseball après un accrochage.",
        "Repérages photographiques d'une installation militaire sensible.",
        "Braquage d'une pharmacie à main armée en cours.",
        "Déséquilibré hurlant des propos incohérents avec une barre de fer.",
        "Vitrine brisée (voiture-bélier) d'une bijouterie pendant la nuit.",
        "Extorsion (racket) de collégiens à la sortie des cours.",
        "Affrontement armé entre deux bandes rivales dans un parc.",
        "Disparition inquiétante d'un mineur depuis plus de 24h.",
        "Survol de drone interdit au-dessus d'une centrale nucléaire.",
        "Tirs d'armes à feu entendus dans un quartier réputé calme.",
        "Vol à l'étalage violent, le vigile est pris à partie.",
        "Voisin tirant au plomb sur les chats du quartier."
    ],
    "POMPIER": [
        "Feu de friteuse propagé à la hotte aspirante.",
        "Début de feu de forêt à proximité d'un camping.",
        "Désincarcération nécessaire suite à un accident frontal.",
        "Incendie d'un appartement au 3ème avec personnes au balcon.",
        "Explosion de bouteille de gaz détruisant un pavillon.",
        "Fuite de gaz de ville dans un hall d'immeuble, forte odeur.",
        "Personne coincée dans un ascenseur bloqué entre deux étages.",
        "Feu de véhicule électrique dans un parking souterrain fermé.",
        "Effondrement d'un plancher vétuste dans un vieil immeuble.",
        "Grange agricole totalement embrasée, menace la maison.",
        "Feux de poubelles alignées le long d'une façade en bois.",
        "Câble haute-tension tombé sur la voie publique après la tempête.",
        "Dégagement de fumée noire depuis une bouche de métro.",
        "Accident impliquant un camion-citerne (matières dangereuses).",
        "Sauvetage d'un ouvrier bloqué sur la flèche d'une grue.",
        "Feu de cheminée classique mais avec risque d'extension toiture.",
        "Bateau de plaisance prenant l'eau à 100m de la côte.",
        "Éboulement rocheux bloquant totalement une départementale.",
        "Ouvrier enseveli dans une tranchée de chantier de voirie.",
        "Alarme incendie généralisée dans un EHPAD (maison de retraite).",
        "Inondation de sous-sol avec compteurs électriques sous l'eau.",
        "Mélange toxique de produits d'entretien dans les cuisines d'un restaurant.",
        "Cheval de 500kg embourbé dans un marais.",
        "Échafaudage de 5 étages menaçant de s'effondrer sur les passants.",
        "Feu de transformateur Enedis avec arcs électriques.",
        "Personne suspendue dans le vide suite à une tentative de suicide ratée.",
        "Feu de broussailles attisé par le Mistral.",
        "Toit d'un supermarché menaçant de céder sous le poids de la neige.",
        "Nid de frelons asiatiques gigantesque dans la cour d'une école.",
        "Dégagement de monoxyde de carbone (CO), famille avec maux de tête.",
        "Fuite d'eau majeure menaçant les archives départementales.",
        "Sauvetage d'un spéléologue coincé dans une galerie.",
        "Incendie de batterie lithium d'une trottinette en charge dans un salon."
    ],
    "RISQUES ENVIRONNEMENTAUX": [
        "Rupture imminente de digue menaçant 5000 habitants.",
        "Nuage de chlore fuyant d'une usine classée Seveso Seuil Haut.",
        "Méga-feu de forêt générant des pyrocumulus et sautant la rivière.",
        "Séisme magnitude 5.5, bâtiments historiques fissurés.",
        "Torrent de boue balayant un village montagnard.",
        "Nappe de pétrole brut s'approchant d'une réserve ornithologique.",
        "Avalanche ayant emporté un groupe de hors-piste.",
        "Incident de niveau 2 sur le site d'une centrale nucléaire.",
        "Microrafale/Tornade détruisant des toitures sur 3 km.",
        "Vague de chaleur extrême, surmortalité détectée dans l'agglomération.",
        "Pollution massive d'un fleuve (eau teintée en rouge fluo).",
        "Invasion de criquets pèlerins ravageant les cultures agricoles.",
        "Émanation de gaz sulfureux depuis une crevasse volcanique.",
        "Tsunami de faible ampleur détecté suite à un séisme sous-marin.",
        "Fonte soudaine du permafrost déstabilisant des infrastructures alpines.",
        "Dépôt sauvage de dizaines de fûts d'amiante en forêt.",
        "Contamination aux PFAS détectée dans la nappe phréatique.",
        "Épisode de pollution aux particules fines nécessitant un confinement.",
        "Multiplication de cas de dengue autochtones liés aux moustiques tigres.",
        "Pluie de grêlons géants détruisant les vitres d'une ville."
    ],
    "CYBERSÉCURITÉ": [
        "Ransomware LockBit chiffrant les serveurs d'un CHU (Hôpital).",
        "Base de données de 5 millions de citoyens fuite sur un forum.",
        "Intrusion réseau réussie via un compte administrateur inactif.",
        "DDoS de 1.2 Tbps ciblant le portail des impôts nationaux.",
        "Détournement BGP redirigeant le trafic bancaire vers des serveurs russes.",
        "Arnaque au faux président (Deepfake audio) avec virement de 2M€.",
        "Désactivation silencieuse des EDR (Antivirus) sur tout le parc machine.",
        "Défacement du site du Ministère de la Défense avec message politique.",
        "Découverte d'une backdoor physique (Raspberry Pi) dans la salle serveur.",
        "Compromission d'un sous-traitant (Supply Chain Attack) via mise à jour logicielle.",
        "Campagne massive de Phishing imitant les RH avec pièce jointe vérolée.",
        "Mineurs de cryptomonnaie déployés illégalement sur l'infrastructure cloud.",
        "Fuite du code source d'une application militaire classifiée.",
        "Manipulation de données SCADA dans une usine de traitement des eaux.",
        "Vol de jetons d'authentification (Tokens) permettant de contourner le MFA.",
        "Vulnérabilité Zero-Day activement exploitée sur les pare-feux Fortinet.",
        "Employé malveillant supprimant massivement des backups avant son départ.",
        "Exfiltration de données à bas bruit via des requêtes DNS.",
        "Pirate demandant une rançon pour ne pas publier des photos médicales.",
        "Réseau Wi-Fi public d'une gare compromis par une attaque Man-in-the-Middle."
    ],
    "ÉNERGIE & INFRASTRUCTURES": [
        "Blackout total sur la moitié du pays suite à une chute de fréquence.",
        "Explosion de la conduite d'eau principale, cratère de 5m dans la rue.",
        "Groupes électrogènes d'un datacenter en panne de fioul.",
        "Chute dramatique d'un pylône THT de 400kV sur une zone commerciale.",
        "Panne du système de refroidissement d'un réacteur nucléaire.",
        "Perte totale de charge sur le réseau de chaleur urbain par -10°C.",
        "Rupture de caténaire sur la ligne TGV Paris-Lyon.",
        "Court-circuit massif incendiant un poste de transformation de quartier.",
        "Fissuration alarmante du béton sur le barrage hydroélectrique.",
        "Baisse de pression critique sur le réseau de gaz naturel haute pression.",
        "Sabotage coordonné de plusieurs câbles sous-marins fibre optique.",
        "Éolienne en feu dont les pales en flammes s'effondrent sur une route.",
        "Infiltration d'eau salée dans l'usine de dessalement d'eau potable.",
        "Effondrement d'un pont routier ancien suite au passage d'un convoi exceptionnel.",
        "Fuite d'hydrogène dans une nouvelle station-service verte.",
        "Surcharge du réseau électrique due à des pics de recharge de véhicules.",
        "Arrêt d'urgence non planifié de la principale raffinerie de pétrole.",
        "Panne informatique du système de distribution d'eau (vannes bloquées).",
        "Incendie d'un gigantesque parc de panneaux solaires.",
        "Glissement de terrain menaçant les fondations d'un viaduc autoroutier."
    ],
    "TRANSPORT & MOBILITÉ": [
        "Eurostar bloqué dans le tunnel sous la Manche sans ventilation.",
        "Collision frontale entre un car scolaire et un train de marchandises.",
        "Aiguillage gelé bloquant tous les trains au départ de la Gare du Nord.",
        "Individu armé signalé dans les couloirs du métro parisien.",
        "Atterrissage d'urgence d'un Airbus A320 avec train d'atterrissage bloqué.",
        "Carambolage de 50 véhicules sur l'A13 à cause d'un brouillard givrant.",
        "Navire méthanier en dérive menaçant de s'échouer sur les côtes.",
        "Déraillement d'un train de fret transportant de l'ammoniac.",
        "Caténaire arrachée par un camion grue sur un passage à niveau.",
        "Système radar de la tour de contrôle en panne logicielle complète.",
        "Prise d'otage ou passager violent enfermé dans l'avion.",
        "Fermeture immédiate de l'espace aérien suite à l'apparition de drones.",
        "Rupture des amarres d'un porte-conteneurs lors d'une tempête au port.",
        "Bus articulé en feu en plein centre historique de la ville.",
        "Grève sauvage des contrôleurs aériens, milliers de passagers bloqués.",
        "Éboulement bloquant la seule route d'accès à une station de ski.",
        "Panne générale du système de billetterie et portiques SNCF.",
        "Fuite de carburant majeure sur le tarmac de l'aéroport.",
        "Véhicule à contre-sens signalé sur l'autoroute A7.",
        "Ferry prenant l'eau avec 800 passagers à bord."
    ],
    "SERVICES URBAINS": [
        "Désynchronisation de tous les feux tricolores créant le chaos.",
        "Formation d'un sinkhole (trou géant) avalant une voiture stationnée.",
        "Blackout de l'éclairage public favorisant la criminalité nocturne.",
        "Refoulement d'égouts inondant la mairie de matières fécales.",
        "Chute d'un arbre centenaire sur le tramway en circulation.",
        "Échafaudage de voirie menaçant de s'effondrer avec le vent.",
        "Amas de déchets bloquant un canal et provoquant une crue.",
        "Sangliers chargeant les passants en plein centre-ville.",
        "Rupture de canalisation d'eau créant une patinoire géante par -5°C.",
        "Sirène d'alerte aux populations déclenchée par erreur à 3h du matin.",
        "Dépôt d'ordures non ramassé depuis 3 semaines, invasion de rats.",
        "Fontaine publique contaminée moussant sur toute la place.",
        "Plaque d'égout disparue au milieu de la route, piège mortel pour les motos.",
        "Feu de conteneur poubelle sous les fenêtres d'un musée d'art.",
        "Panneau publicitaire géant arraché par le vent.",
        "Banc public vandalisé, morceaux de métal tranchants exposés.",
        "Fuite de chlore à la piscine municipale nécessitant évacuation.",
        "Nid de guêpes géant dans un abribus.",
        "Inondation du cimetière municipal provoquant des affaissements.",
        "Affaissement du trottoir fragilisant les fondations des immeubles."
    ],
    "ASSISTANCE SOCIALE": [
        "Découverte d'un homme sans-abri inanimé dans le gel.",
        "Enfant de 5 ans en larmes ne retrouvant plus ses parents au marché.",
        "Personne âgée désorientée cherchant son mari décédé depuis 10 ans.",
        "Femme fuyant des coups demandant asile d'urgence avec son bébé.",
        "Individu prêt à sauter depuis le toit d'un centre commercial.",
        "Famille avec bébés mise à la rue suite à une expulsion locative.",
        "Jeune en crise psychotique hurlant et se frappant la tête dans un parc.",
        "Appel de détresse d'une personne isolée sans électricité ni nourriture.",
        "Campement de Roms installé sur une zone inondable en crue.",
        "Signalement de cris d'enfants continus et de bruits de coups.",
        "Mineur isolé étranger (MIE) dormant dans une gare par temps froid.",
        "Personne handicapée coincée chez elle suite à une panne d'ascenseur.",
        "Violente dispute entre SDF pour une place dans la rue.",
        "Appel silencieux au 114 (SMS d'urgence) demandant discrètement de l'aide.",
        "Victime de violences signalant que son agresseur approche.",
        "Personne âgée signalant qu'on lui vole son argent de force.",
        "Prostitution de mineur suspectée dans un squat voisin.",
        "Découverte d'une personne vivant au milieu de ses déjections (Syndrome de Diogène).",
        "Évacuation d'urgence d'un EHPAD sans chauffage l'hiver.",
        "Risque d'accouchement prématuré dans un bidonville."
    ],
    "DIGITAL SUPPORT": [
        "Oubli du mot de passe de session Windows par le nouveau collaborateur.",
        "Serveur DNS interne bloqué, impossible d'accéder à l'Intranet.",
        "Imprimante de production industrielle en erreur 'Bourrage Papier F4'.",
        "Perte du badge physique d'accès aux locaux sensibles.",
        "Écran bleu de la mort (BSOD) sur le PC portable du Directeur.",
        "Logiciel de paie RH inaccessible à J-1 du virement des salaires.",
        "Tapis roulant de l'entrepôt logistique arrêté par un bug automate.",
        "VPN saturé, les télétravailleurs sont déconnectés toutes les 5 minutes.",
        "Caméra de surveillance de l'entrée qui filme en noir et blanc brouillé.",
        "Serveur de logs saturé à 100%, ralentissant les applications tierces.",
        "Employé ayant laissé un prestataire externe utiliser sa session.",
        "Tablette de préparation de commande en entrepôt qui ne charge plus.",
        "Climatisation de la baie de brassage IT en panne, il fait 35°C.",
        "Terminal de paiement (TPE) du magasin affichant 'HORS LIGNE'.",
        "Suppression accidentelle du dossier 'FINANCES 2024' sur le réseau partagé.",
        "Visiteur VIP bloqué dans le sas de sécurité à cause du biométrique.",
        "Erreur 500 sur l'application métier lors de la génération de factures.",
        "Smartphone professionnel volé non protégé par un mot de passe.",
        "L'application Microsoft Teams refuse de partager l'écran en réunion CODIR.",
        "Câble RJ45 coupé par mégarde sous le bureau de l'assistante.",
        "Mise à jour Windows bloquée à 99% depuis 3 heures.",
        "Lecteur de code-barres industriel qui bipe sans rien scanner.",
        "Double appel téléphonique impossible sur le standard IP (VoIP).",
        "Le projecteur de la grande salle de réunion affiche une couleur rose.",
        "Un employé a renversé du café sur le clavier de l'ordinateur central."
    ],
    "ANIMALIER": [
        "Chien percuté par une voiture, il saigne abondamment sur le bas-côté.",
        "Chat coincé en haut d'un poteau électrique haute tension depuis 24h.",
        "Troupeau de vaches ou de chevaux divaguant au milieu de l'autoroute.",
        "Découverte d'un dauphin échoué et encore vivant sur la plage.",
        "Signalement de maltraitance animale grave en cours chez un voisin.",
        "Cheval de 500kg embourbé dans un marécage, il s'enfonce.",
        "Serpent exotique (gros python) retrouvé dans les toilettes d'un appartement.",
        "Chien enfermé dans une voiture en plein soleil pendant une canicule.",
        "Sanglier très agressif bloqué dans la cour d'une école primaire.",
        "Chien de catégorie 1 (Pitbull) très menaçant en liberté dans un parc public.",
        "Rapace protégé (Aigle/Faucon) blessé à l'aile trouvé dans le jardin.",
        "Nid de frelons asiatiques géant à hauteur d'enfant dans un square."
    ]
}