# executives/nexus_matrix.py

DOMAINES = ["MÉDICAL", "POLICE", "POMPIER", "INFRA", "ACCÈS", "MATÉRIEL"]

PERSONAS = [
    {"profil": "Novice paniqué", "instruction": "Tu es terrifié, tu parles de manière confuse, tu utilises des mots simples et tu cries presque."},
    {"profil": "Expert technique", "instruction": "Tu es très calme. Tu utilises un vocabulaire précis (codes d'erreur, termes médicaux ou juridiques). Tu vas droit au but."},
    {"profil": "Personne âgée", "instruction": "Tu prends ton temps, tu racontes un peu ta vie avant de donner le problème exact. Tu ne comprends pas bien les termes techniques."},
    {"profil": "Passant pressé", "instruction": "Tu as vu un incident dans la rue. Tu es pressé, tu donnes le minimum d'informations et tu veux raccrocher vite."},
    {"profil": "Professionnel de santé hors service", "instruction": "Tu es médecin ou infirmier mais tu n'es pas en service. Tu utilises le jargon médical précis mais tu es émotionnellement impliqué car c'est un proche."},
    {"profil": "Enfant seul", "instruction": "Tu as entre 8 et 12 ans. Tu pleures un peu. Tu ne connais pas ton adresse exacte. Tu décris les choses avec des mots d'enfant."},
    {"profil": "Témoin choqué", "instruction": "Tu viens d'assister à quelque chose de traumatisant. Tu bégaies parfois, tu reviens en arrière dans ton récit, tu as du mal à être chronologique."},
    {"profil": "Non-francophone débrouillard", "instruction": "Tu parles français avec difficulté. Tu mélanges parfois avec ta langue maternelle. Tu répètes les mots qu'on te dit pour confirmer."},
    {"profil": "Collègue de travail pragmatique", "instruction": "Tu signales un incident au bureau. Tu es calme, factuel, tu donnes les numéros de salle, noms de machines et procédures déjà tentées."},
    {"profil": "Personne malvoyante", "instruction": "Tu ne vois pas bien. Tu décris ce que tu entends, ce que tu ressens. Tu ne peux pas lire les numéros ou panneaux."},
    {"profil": "Client en colère", "instruction": "Tu es extrêmement frustré par l'attente ou le problème. Tu es agressif verbalement, tu coupes la parole et tu menaces de porter plainte."},
    {"profil": "Adolescent désinvolte", "instruction": "Tu utilises beaucoup d'argot, tu sembles ne pas réaliser la gravité de la situation, tu es distrait par ton environnement."},
    {"profil": "Parent épuisé", "instruction": "Tu as un enfant qui hurle en fond. Tu es à bout de nerfs, tu perds le fil de tes phrases, tu demandes de l'aide de manière désespérée mais polie."},
    {"profil": "Sarcastic/Blasé", "instruction": "Tu as déjà appelé dix fois. Tu es cynique, tu penses que rien ne sera fait, tu commentes l'inefficacité du service."},
    {"profil": "Individu sous le choc (calme blanc)", "instruction": "Tu es étrangement calme, presque déconnecté de la réalité. Tes phrases sont courtes, dénuées d'émotion, comme un automate."}
]

CONTRAINTES_ENVIRONNEMENT = [
    "Il y a beaucoup de bruit de fond (circulation, alarmes).",
    "La connexion téléphonique est mauvaise, tu dois parfois te répéter.",
    "Tu es caché (ex: cambriolage ou violence) et tu dois chuchoter (phrases très courtes).",
    "Environnement calme, bureau silencieux.",
    "Tu es dans un ascenseur, le signal est intermittent. Tu disparais et réapparais.",
    "Tu appelles depuis les toilettes d'un bâtiment pour ne pas être entendu.",
    "Il y a plusieurs personnes autour qui parlent en même temps, tu relais leurs informations.",
    "Tu es en voiture, tu conduis encore et tu parles en mains-libres, légèrement distrait.",
    "La batterie de ton téléphone est à 2%, tu es très pressé.",
    "Tu as les mains occupées (blessure compressée, enfant dans les bras), tu parles avec difficulté.",
    "Tu es dans un ascenseur, le signal est intermittent. Tu disparais et réapparais.",
    "Tu appelles depuis les toilettes d'un bâtiment pour ne pas être entendu.",
    "Il y a plusieurs personnes autour qui parlent en même temps, tu relais leurs informations.",
    "Tu es en voiture, tu conduis encore et tu parles en mains-libres, légèrement distrait.",
    "La batterie de ton téléphone est à 2%, tu es très pressé.",
    "Tu as les mains occupées (blessure compressée, enfant dans les bras), tu parles avec difficulté.",
    "Vent violent qui sature le micro de ton téléphone.",
    "Tu es dans un tunnel ou un parking souterrain, il y a un écho énorme.",
    "Musique de boîte de nuit ou de festival très forte en arrière-plan.",
    "Tu es en train de courir, tu es essoufflé et on entend tes pas saccadés.",
    "Sirènes de police ou de pompiers qui passent juste à côté de toi pendant l'appel.",
    "Tu es dans un environnement très froid (extérieur en hiver), tu claques des dents en parlant."
]

SCENARIOS = {
    "MÉDICAL": [
        "Infarctus du myocarde (douleur poitrine, bras gauche).",
        "Chute dans les escaliers avec suspicion de fracture ouverte à la jambe.",
        "Réaction allergique grave (choc anaphylactique) après un repas.",
        "Simple coupure au doigt, mais tu as très peur du sang.",
        "Enfant de 3 ans qui a avalé des médicaments trouvés dans le placard.",
        "Femme enceinte à 8 mois avec des contractions toutes les 2 minutes.",
        "Personne inconsciente sur un banc public, respiration irrégulière.",
        "Crise d'épilepsie dans un supermarché, la personne convulse encore.",
        "Douleur thoracique aiguë chez un homme de 65 ans sous anticoagulants.",
        "Brûlure grave au troisième degré après un accident de cuisine.",
        "Tentative de suicide découverte, la personne est semi-consciente.",
        "AVC suspecté : visage qui tombe, bras qui ne répond plus, parole confuse.",
        "Nourrisson de 6 mois qui ne respire plus normalement depuis 10 minutes.",
        "Diabétique en hypoglycémie sévère, ne reconnaît plus ses proches.",
        "Corps étranger bloqué dans la gorge, l'enfant commence à bleuir.",
        "Plaie par balle, présumée accidentelle, saignement abondant.",
        "Douleur abdominale intense depuis 6h, vomissements, impossible de se tenir debout.",
        "Personne âgée désorientée retrouvée errant dehors en pyjama en pleine nuit.",
        "Chute de vélo sans casque, perte de connaissance de quelques secondes.",
        "Fièvre à 40°C chez un enfant, ne réagit presque plus.",
        "Douleur soudaine dans le dos irradiant vers la poitrine, sueurs froides.",
        "Plaie profonde avec objet encore planté dans la cuisse.",
        "Difficulté respiratoire progressive depuis 2 jours, aggravation brutale ce soir.",
        "Vomissements avec présence de sang rouge vif.",
        "Main coincée dans une machine, doigts écrasés mais personne consciente.",
        "Personne qui délire, parle seule, comportement incohérent depuis plusieurs heures.",
        "Crise d'asthme sévère, inhalateur inefficace.",
        "Morsure de chien avec plaie ouverte et saignement important.",
        "Surdose médicamenteuse suspectée, pupilles contractées et somnolence extrême.",
        "Hypothermie sévère : personne retrouvée dans l'eau glacée, ne parle plus.",
        "Accouchement imminent dans une voiture sur le bas-côté.",
        "Hémorragie post-partum à domicile, la patiente perd connaissance.",
        "Suspicion de méningite chez un ado : forte fièvre, raideur de nuque et taches sur la peau.",
        "Tentative d'autolyse par défenestration, la personne est sur le rebord de la fenêtre.",
        "Douleur violente et soudaine dans l'œil avec perte de vision immédiate.",
        "Traumatisme crânien après une chute de cheval, amnésie post-traumatique.",
    ],
    "POLICE": [
        "Cambriolage en cours, les voleurs sont dans le salon.",
        "Découverte de ta voiture avec la vitre brisée ce matin.",
        "Individu armé d'un couteau qui menace des passants.",
        "Tapage nocturne insupportable chez les voisins.",
        "Femme qui crie à l'aide depuis un appartement au 3ème étage.",
        "Homme qui suit une femme depuis 20 minutes dans la rue.",
        "Accident de voiture avec délit de fuite, tu as la plaque.",
        "Bagarre générale devant une discothèque, plusieurs personnes à terre.",
        "Enfant seul dans la rue depuis 2 heures, pleure, ne sait pas où il habite.",
        "Personne agressive dans le métro qui frappe des passagers au hasard.",
        "Véhicule suspect garé devant une école, moteur tournant depuis 1h.",
        "Violence conjugale audible à travers le mur, coups et cris.",
        "Escroquerie en direct : un faux technicien dans l'appartement d'une voisine âgée.",
        "Tag sur une façade en train d'être fait, tu filmes les auteurs.",
        "Menace de mort reçue par SMS avec adresse personnelle.",
        "Individu qui observe des enfants dans un parc de manière suspecte depuis 1h.",
        "Individu qui tente d'ouvrir plusieurs voitures sur un parking souterrain.",
        "Groupe de personnes encagoulées qui rôdent autour d'un entrepôt fermé.",
        "Altercation verbale qui dégénère dans un bus, chauffeur dépassé.",
        "Tentative d'enlèvement suspectée, enfant tiré par le bras dans la rue.",
        "Colis abandonné dans une gare, personne ne sait d'où il vient.",
        "Rodéo urbain avec motos sans plaques dans un quartier résidentiel.",
        "Personne ivre qui bloque la circulation en plein carrefour.",
        "Dispute violente entre deux conducteurs après un accrochage.",
        "Individu qui filme les entrées d'un bâtiment sensible de manière répétée.",
        "Tentative d'effraction sur une porte d'immeuble en pleine journée.",
        "Homme qui hurle des propos incohérents et effraie les passants.",
        "Vitrine de magasin brisée, personne à proximité, auteur inconnu.",
        "Cyber-harcèlement en direct : quelqu'un menace de diffuser des photos privées maintenant.",
        "Rixe impliquant des armes blanches dans un parc public entre deux bandes.",
        "Disparition inquiétante d'une personne atteinte d'Alzheimer depuis 4 heures.",
        "Drone suspect survolant une zone militaire ou un site sensible de manière répétée.",
        "Tentative d'extorsion de fonds dans un commerce par deux individus masqués.",
        "Vandalisme de masse sur un monument historique en cours.",
        "Voisin qui tire des coups de feu en l'air avec un fusil de chasse dans son jardin.",
        "Signalement d'un colis suspect avec des fils apparents dans une poubelle de centre commercial.",
    ],
    "INFRA": [
        "Le serveur principal de base de données est en Kernel Panic.",
        "Plus de connexion Internet sur tout le site de l'entreprise à Paris.",
        "Attaque Ransomware détectée, les fichiers se cryptent en direct.",
        "Coupure électrique totale dans le datacenter, les onduleurs tiennent 20 minutes.",
        "Fuite d'eau dans la salle serveurs, l'eau touche les baies.",
        "Pic de charge inattendu sur l'API de paiement, timeout en cascade.",
        "Certificat SSL expiré sur le site e-commerce principal, ventes bloquées.",
        "Base de données corrompue après migration ratée, rollback impossible.",
        "Attaque DDoS en cours, 800Gbps absorbés, CDN commence à lâcher.",
        "Disque RAID0 en défaillance, données non sauvegardées depuis 36h.",
        "Déploiement en production qui a cassé l'authentification pour tous les users.",
        "Accès SSH root compromis, commandes suspectes dans les logs depuis 3h.",
        "Température salle serveurs à 42°C, climatisation en panne.",
        "Sauvegarde quotidienne corrompue depuis 10 jours, découverte ce matin.",
        "Coupure fibre opérateur principal, lien de secours saturé à 100%.",
        "Service DNS interne indisponible, tous les services deviennent inaccessibles.",
        "Horloge système désynchronisée, erreurs d'authentification généralisées.",
        "Pipeline CI/CD bloqué, aucun déploiement possible depuis 12h.",
        "Quota disque atteint sur serveur critique, logs ne s'écrivent plus.",
        "Cluster Kubernetes instable, pods redémarrent en boucle.",
        "Erreur de configuration réseau, trafic interne redirigé vers l'extérieur.",
        "API tierce critique indisponible, dépendance bloquante pour les clients.",
        "Cache distribué corrompu, données incohérentes renvoyées aux utilisateurs.",
        "Perte partielle de données après suppression accidentelle en production.",
        "Failover automatique qui ne s'est pas déclenché lors d'une panne.",
        "Surcharge CPU à 100% sur tous les nœuds applicatifs.",
        "Logs de sécurité supprimés ou altérés, suspicion de dissimulation.",
        "Erreur de manipulation : suppression accidentelle du bucket S3 de production.",
        "Détection d'un point d'accès Wi-Fi pirate (Rogue AP) sur le réseau corporate.",
        "Coupure de fibre majeure causée par un engin de chantier devant le siège.",
        "Mise à jour firmware ayant 'briqué' tous les terminaux de paiement du magasin.",
        "Fuite de données massives détectée sur un forum de hackers, originaire de nos serveurs.",
        "BGP Hijacking suspecté : le trafic vers nos services est redirigé vers l'étranger.",
        "Serveur de téléphonie IP (VoIP) HS, plus aucun appel sortant possible.",
        "Dysfonctionnement du système de refroidissement liquide, fuite sur les lames de calcul.",
    ],
    "POMPIER": [
        "Incendie dans une cuisine, les flammes se propagent au rideau.",
        "Feu de forêt qui approche d'une zone résidentielle, odeur de fumée dense.",
        "Personne coincée dans une voiture accidentée sur l'autoroute, véhicule qui fume.",
        "Immeuble de 5 étages en feu, cris aux fenêtres, personnes bloquées.",
        "Explosion de gaz dans un sous-sol d'immeuble, mur fissuré.",
        "Fuite de gaz naturel dans un appartement, odeur très forte, voisins évacués.",
        "Noyade d'un enfant dans une piscine privée, parents en panique.",
        "Personne coincée dans un ascenseur depuis 45 minutes, chaleur excessive.",
        "Feu de véhicule électrique sur parking souterrain, fumée noire.",
        "Effondrement partiel d'un plancher, une personne est tombée au sous-sol.",
        "Inondation rapide au rez-de-chaussée après orage, eau monte vite.",
        "Grange en feu avec des animaux à l'intérieur, exploitant agricole appelle.",
        "Feu de poubelle qui commence à atteindre une façade d'immeuble.",
        "Odeur de brûlé persistante dans un immeuble sans source visible.",
        "Câble électrique tombé au sol après tempête, étincelles visibles.",
        "Fumée qui sort d'une bouche d'égout en pleine rue.",
        "Accident de la route avec véhicule retourné et fuite de carburant.",
        "Personne coincée sur un toit après avoir tenté de fuir un incendie.",
        "Feu de cheminée avec flammes visibles en toiture.",
        "Bateau en train de prendre l'eau au port, occupants paniqués.",
        "Éboulement de terrain bloquant une route départementale.",
        "Ouvrier enseveli partiellement sur un chantier après effondrement.",
        "Feu dans un local technique d'un immeuble, alarme déclenchée.",
        "Fuite d'eau massive dans un parking souterrain, véhicules immergés.",
        "Fuite de produit chimique inconnu dans un laboratoire de lycée, picotements aux yeux.",
        "Sauvetage animalier technique : cheval embourbé dans un marécage qui s'enfonce.",
        "Effondrement d'un échafaudage sur la voie publique avec passants dessous.",
        "Feu de transformateur électrique haute tension avec arcs électriques impressionnants.",
        "Inondation de sous-sol avec risque d'électrocution (compteurs immergés).",
        "Personne bloquée sur une nacelle de laveur de vitres à 15 mètres de haut.",
        "Feu de forêt avec propagation rapide due à des vents tournants.",
        "Accumulation de neige sur une toiture fragile menaçant de s'effondrer sur une école.",
    ],
    "ACCÈS": [
        # Domaine vide dans l'original
        "Badge de sécurité perdu dans les transports, accès à une zone sensible possible.",
        "Collaborateur licencié la semaine dernière tente d'accéder au bâtiment avec son ancien badge.",
        "Visiteur non enregistré qui insiste pour entrer sans rendez-vous.",
        "Porte coupe-feu du 3ème étage ne se ferme plus, alarme incendie active.",
        "Sas d'entrée bloqué en position ouverte depuis 1 heure.",
        "Code PIN de la salle serveurs modifié par erreur, toute l'équipe est dehors.",
        "Individu qui se fait passer pour un technicien de maintenance sans accréditation.",
        "Accès au parking souterrain bloqué, barrière coincée, 30 voitures en attente.",
        "Compte administrateur verrouillé après trop de tentatives de connexion échouées.",
        "Clé maîtresse d'un étage entier disparue après un déménagement de bureau.",
        "Système de contrôle d'accès biométrique hors service, 200 employés bloqués.",
        "Tentative d'intrusion détectée sur une porte de secours, capteur déclenché.",
        "Employé qui prête son badge à un inconnu 'pour dépanner'.",
        "Personne qui force le passage derrière un employé (tailgating).",
        "Badge actif pour un ancien prestataire parti depuis 6 mois.",
        "Agent de sécurité absent de son poste depuis 30 minutes.",
        "Caméra de surveillance orientée vers un mur depuis ce matin.",
        "Liste des accès imprimée retrouvée dans un espace public.",
        "Utilisateur qui note son code d'accès sur un post-it visible.",
        "Accès VPN ouvert depuis un pays inhabituel pour un employé.",
        "Plusieurs tentatives d'accès avec différents badges sur une même porte.",
        "Porte sécurisée maintenue ouverte avec un objet.",
        "Compte utilisateur partagé entre plusieurs personnes.",
        "Demande urgente d'accès 'exceptionnel' sans validation hiérarchique.",
        "Sabotage du lecteur de badge à l'entrée principale (glu ou fils coupés).",
        "Accès forcé via une fenêtre du rez-de-chaussée laissée entrebâillée.",
        "Clés de haute sécurité d'un coffre-fort introuvables après le passage du ménage.",
        "Dépassement du temps d'ouverture d'une zone sécurisée (Time-out alarme).",
        "Utilisation frauduleuse d'un code de secours 'urgence' sans raison valable.",
        "Panne du système d'interphonie, les visiteurs attendent sous la pluie.",
        "Alarme périmétrique déclenchée par un animal, mais levée de doute impossible (caméra HS).",
        "Badge VIP volé lors d'un 'pickpocket' à la sortie du métro.",
    ],
    "MATÉRIEL": [
        # Domaine vide dans l'original
        "Imprimante industrielle en panne, production bloquée, deadline dans 2h.",
        "Fuite hydraulique sur une machine-outil, huile sur le sol, risque de glissade.",
        "Grue de chantier qui émet des bruits anormaux en pleine opération de levage.",
        "Générateur de secours refusé de démarrer lors d'un test de routine.",
        "Convoyeur de production arrêté subitement, bouchon sur toute la chaîne.",
        "Scanner médical IRM en surchauffe, patients en attente replanifiés.",
        "Chariot élévateur avec frein défaillant dans un entrepôt de produits chimiques.",
        "Ascenseur de charge bloqué avec une palette à mi-hauteur, bloque un couloir.",
        "Câble d'alimentation 400V dénudé découvert dans une armoire électrique ouverte.",
        "Groupe électrogène qui consomme anormalement, réservoir quasi vide.",
        "Robot de soudure déréglé, cordons hors tolérance, série entière à revoir.",
        "Climatiseur de salle blanche en panne, salle ISO5 hors norme, production stoppée.",
        "Machine qui vibre anormalement depuis plusieurs heures.",
        "Odeur de plastique brûlé provenant d'une armoire électrique.",
        "Écran de contrôle qui affiche des valeurs incohérentes.",
        "Baisse progressive de pression dans un circuit hydraulique.",
        "Alarme intermittente sur un équipement critique sans cause identifiée.",
        "Fissure visible sur une pièce mécanique en rotation.",
        "Temps de réponse anormalement long sur une machine automatisée.",
        "Ventilation bruyante et inefficace sur un équipement sensible.",
        "Arrêts/redémarrages fréquents d'un système sans intervention humaine.",
        "Capteur de sécurité désactivé pour 'gagner du temps'.",
        "Consommation électrique anormalement élevée sur une ligne.",
        "Équipement utilisé hors de ses spécifications nominales.",
        "Défaillance d'un EPI (harnais de sécurité) lors d'un travail en hauteur.",
        "Explosion d'une batterie de chariot élévateur en charge dans l'entrepôt.",
        "Laser de découpe industrielle décalibré provoquant des débuts d'incendie sur le bois.",
        "Rupture d'un flexible hydraulique haute pression sur une presse.",
        "Écran de monitoring médical qui s'éteint pendant une intervention.",
        "Imprimante 3D de prototypage qui s'enflamme suite à un court-circuit.",
        "Bruit de roulement métallique suspect sur l'extracteur d'air principal.",
        "Capteur de température défectueux sur une cuve de produits inflammables."
    ]
}